const fs = require('fs');
const path = require('path');
const manualCatalog = require('./manual.config.js');

const docsDir = path.join(__dirname, 'docs');

const docId = (bundle, doc) => `${bundle.path}/${doc.id}`;

const docExists = (id) =>
  ['.mdx', '.md'].some((extension) => fs.existsSync(path.join(docsDir, `${id}${extension}`)));

const assertDocExists = (id, ownerLabel) => {
  if (!docExists(id)) {
    throw new Error(`[manual.config.js] ${ownerLabel} references missing doc: docs/${id}.mdx`);
  }
};

const assertConditionEntryExists = (app, condition) => {
  const entryId = `${app.path}/${condition.path}/index`;
  assertDocExists(entryId, `${app.label} > ${condition.label}`);
};

const explicitSidebar = (bundle) =>
  bundle.docs.map((doc) => {
    const id = docId(bundle, doc);
    assertDocExists(id, bundle.label);

    return {
      type: 'doc',
      id
    };
  });

const sidebars = {};

for (const app of manualCatalog.apps) {
  sidebars[app.sidebarId] = explicitSidebar(app);

  for (const condition of app.conditions ?? []) {
    assertConditionEntryExists(app, condition);

    sidebars[condition.sidebarId] = [
      {
        type: 'autogenerated',
        dirName: `${app.path}/${condition.path}`
      }
    ];
  }
}

for (const developerDoc of manualCatalog.developerDocs) {
  sidebars[developerDoc.sidebarId] = explicitSidebar(developerDoc);
}

module.exports = sidebars;
